openfruit/taxonomy/urls.py
from django.conf.urls import url
from openfruit.taxonomy import views
from openfruit.taxonomy.views import GenusListView, KingdomListView, \
    GenusDetailView, SpeciesDetailView, CultivarDetailView, SpeciesAutocomplete, \
    CultivarAutocomplete, GenusAutocomplete, GenusFormView, PublicPlantsView, FruitingPlantAutocomplete, \
    move_fruiting_plant, FruitingPlantFormView, Cultivar, SpeciesFormView, cultivar_detail_view_redirect, \
    FruitingPlantDetailsView, FruitUsageTypeDetailView, search, species_detail_view_redirect


urlpatterns = [
    url(r'^search/$', search, name='search'),

    url(r'^browse/(?P<kingdom>.+)/(?P<genus>.+)/(?P<species>.+)/(?P<cultivar>.+)$', CultivarDetailView.as_view(), name='cultivar-detail'),
    url(r'^browse/(?P<kingdom>.+)/(?P<genus>.+)/(?P<species>.+)$', SpeciesDetailView.as_view(), name='species-detail'),
    url(r'^browse/(?P<kingdom>.+)/(?P<genus>.+)$', GenusDetailView.as_view(), name='genus-detail'),
    url(r'^browse/(?P<kingdom>.+)$', GenusListView.as_view(), name='genus-list'),
    url(r'^browse/$', KingdomListView.as_view(), name='browse'),

    url(r'^genus/(?P<id>\d+)?$', GenusFormView.as_view(), name='genus'),
    url(r'^genus/(?P<genusID>\d+)/species/(?P<id>\d+)?$', SpeciesFormView.as_view(), name='species'),
    url(r'^cultivar/(?P<cultivar_id>\d+)', cultivar_detail_view_redirect, name='cultivar-detail-redirect'),
    url(r'^species/(?P<species_id>\d+)', species_detail_view_redirect, name='species-detail-redirect'),

    url(r'^fruiting-plant/(?P<id>\d+)?$', FruitingPlantFormView.as_view(), name='fruiting-plant'),
    url(r'^fruiting-plant/details/(?P<id>\d+)?$', FruitingPlantDetailsView.as_view(), name='fruiting-plant-details'),

    url('^autocomplete/genus/$', GenusAutocomplete.as_view(), name='genus-autocomplete'),
    url('^autocomplete/species/$', SpeciesAutocomplete.as_view(), name='species-autocomplete'),
    url('^autocomplete/cultivar/$', CultivarAutocomplete.as_view(model=Cultivar,
            create_field='name',), name='cultivar-autocomplete'),
    url('^autocomplete/fruiting-plant/$', FruitingPlantAutocomplete.as_view(), name='fruiting-plant-autocomplete'),

    url('^api/v1/plants/move$', move_fruiting_plant, name='move_fruiting_plant'),
    url('^api/v1/plants/public/$', PublicPlantsView.as_view(), name='public_plants_without_user'),
    url(r'^api/v1/species/(?P<pk>[0-9]+)/$', views.SpeciesDetail.as_view(), name='species-detail'),
    url(r'^api/v1/species_list/$', views.SpeciesListView.as_view(), name='species-list'),
    url(r'^api/v1/fruit-usage-type/$', views.FruitUsageTypeDetailView.as_view(), name='fruitusagetype-detail'),
    url(r'^api/v1/cultivars/$', views.CultivarListView.as_view(), name='cultivar-list'),
    url(r'^api/v1/cultivars/(?P<pk>[0-9]+)/$', views.CultivarDetail.as_view(), name='cultivar-detail'),
    url(r'^api/v1/fruiting-plants/(?P<query>.+)?$', views.PlantsListView.as_view(), name='users-fruiting-plants'),
    url(r'^api/v1/ripenings/$', views.RipeningListView.as_view(), name='ripenings-list'),
    url(r'^api/v1/chromosomes/$', views.ChromosomesListView.as_view(), name='chromosomes-list'),
]

openfruit/urls.py
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.views.generic import TemplateView
from django.contrib import admin
from rest_framework import routers
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token, verify_jwt_token

from openfruit import settings
from openfruit.views import home, about, site_change, testing

router = routers.DefaultRouter()

urlpatterns = [

    url(r'^$', home, name='home'),
    url(r'^about/$', about, name='about'),
    url(r'^terms-of-service/$', TemplateView.as_view(template_name='terms-of-service.html'), name='terms-of-service'),
    url(r'^privacy/$', TemplateView.as_view(template_name='privacy-policy.html'), name='privacy-policy'),
    url(r'^request/site-change/$', site_change, name='site_change'),
    url(r'^admin/', include(admin.site.urls), name='admin'),

    # Authorization
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/v1/auth/token/$', obtain_jwt_token),
    url(r'^api/v1/auth/token/verify/$', verify_jwt_token),
    url(r'^api/v1/auth/token/refresh/$', refresh_jwt_token),
    url(r'^api/v1/auth/rest/', include('rest_auth.urls')),
    url(r'^api/v1/auth/allauth/', include('allauth.urls')),
    url(r'^', include('openfruit.ofauth.urls')),

    # Geo
    url(r'^api/v1/', include('django_geo_db.urls')),
    url(r'^api/v1/', include('django_geo_db.autocomplete_urls')),

    url(r'^', include('openfruit.common.urls')),
    url(r'^', include('openfruit.taxonomy.urls')),
    url(r'^', include('openfruit.reports.event.urls')),
    url(r'^', include('openfruit.reports.review.urls')),
    url(r'^', include('openfruit.userdata.urls')),
    url(r'^', include('openfruit.fruit_search.urls')),
    url(r'^', include('openfruit.geography.urls')),
    url(r'^', include('openfruit.fruit_reference.urls')),
    url(r'^', include('openfruit.reports.disease.urls')),
    url(r'^', include('openfruit.fruit_api.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += router.urls

if settings.DEBUG:
    urlpatterns += [url(r'^testing/$', testing, name='testing'),]

openfruit/taxonomy/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from colorful.fields import RGBColorField
from sorl.thumbnail.fields import ImageField
from openfruit.common.models import IntegerRangeField
from django_geo_db.models import Location, GeoCoordinate
from openfruit.taxonomy.managers import GenusManager, KingdomManager, SpeciesManager, CultivarManager, FruitingPlantManager
from openfruit.taxonomy.mixins import UrlNameMixin

PLANT_KINGDOM_NAMES = (
    'Plants', 'Plantae',
)

CHROMOSOME_CHOICES = (
    ('2', 'Diploid x2'),
    ('3', 'Triploid x3'),
    ('4', 'Tetraploid x4'),
    ('5', 'Pentaploid x5'),
    ('6', 'Hexaploid x6'),
    ('8', 'Octoploid x8'),
)

RIPENING_MODIFIER = (
    ('e', 'Early'),
    ('m', 'Mid'),
    ('l', 'Late'),
)

RIPENING_MONTH_CHOICES = (
    (1, 'January'),
    (2, 'February'),
    (3, 'March'),
    (4, 'April'),
    (5, 'May'),
    (6, 'June'),
    (7, 'July'),
    (8, 'August'),
    (9, 'September'),
    (10, 'October'),
    (11, 'November'),
    (12, 'December'),
    (-1, 'Unknown'),
)

COMMON_USES = [
    'Baking',
    'Cooking',
    'Cider',
    'Drying',
    'Fresh Eating',
    'Preserves',
    'Storage',
]


class Kingdom(models.Model, UrlNameMixin):
    objects = KingdomManager()
    kingdom_id = models.AutoField(primary_key=True)
    latin_name = models.CharField(max_length=30, unique=True)
    name = models.CharField(max_length=30, unique=True)
    featured_image = models.ImageField(upload_to='featured-images', blank=True, null=True)

    def __str__(self):
        return self.latin_name

    class Meta:
        ordering = ('latin_name',)


class Genus(models.Model, UrlNameMixin):
    objects = GenusManager()
    genus_id = models.AutoField(primary_key=True)
    kingdom = models.ForeignKey(Kingdom)
    latin_name = models.CharField(max_length=30, unique=True)
    name = models.CharField(max_length=30)
    featured_image = ImageField(upload_to='featured-images', blank=True, null=True)
    generated_name = models.CharField(max_length=60, unique=True, blank=True, null=True)

    class Meta:
        ordering = ('generated_name',)

    def save(self, *args, **kwargs):
        self.generated_name = self.__get_generated_name()
        return super(Genus, self).save(*args, **kwargs)

    def __str__(self):
        return self.generated_name or self.__get_generated_name()

    def __get_generated_name(self):
        return '{0} ({1})'.format(self.name, self.latin_name)


class Species(models.Model, UrlNameMixin):
    objects = SpeciesManager()
    species_id = models.AutoField(primary_key=True)
    genus = models.ForeignKey(Genus)
    origin = models.ForeignKey(Location, blank=True, null=True)
    latin_name = models.CharField(max_length=30)
    name = models.CharField(max_length=30)
    can_scale_with_pruning = models.BooleanField(default=False)
    years_till_full_size = IntegerRangeField(min_value=1, max_value=100, blank=True, null=True)
    full_size_height = IntegerRangeField(min_value=1, max_value=500, blank=True, null=True)
    full_size_width = IntegerRangeField(min_value=1, max_value=200, blank=True, null=True)
    years_till_first_production = IntegerRangeField(min_value=1, max_value=30, blank=True, null=True)
    years_till_full_production = IntegerRangeField(min_value=1, max_value=100, blank=True, null=True)
    featured_image = ImageField(upload_to='featured-images', blank=True, null=True)
    google_maps_image_url = models.CharField(max_length=100, blank=True, null=True, default=None)
    generated_name = models.CharField(max_length=60, unique=True, blank=True, null=True)

    class Meta:
        ordering = ('generated_name',)
        unique_together = (('genus', 'latin_name'))

    def save(self, *args, **kwargs):
        self.generated_name = self.__get_generated_name()
        return super(Species, self).save(*args, **kwargs)

    def __str__(self):
        return self.generated_name or self.__get_generated_name()

    def __get_generated_name(self):
        return '{0} ({1})'.format(self.name, self.latin_name)


class FruitUsageType(models.Model):
    cultivar_usage_type_id = models.AutoField(primary_key=True)
    type = models.CharField(max_length=40, unique=True)

    def __str__(self):
        return self.type


class Cultivar(models.Model, UrlNameMixin):
    """
    Metadata information related to a specific clonally propagated piece of fruit.
    This model does NOT contain subjective information or information gathered from in the field.
    """
    objects = CultivarManager()
    cultivar_id = models.AutoField(primary_key=True)
    species = models.ForeignKey(Species)
    name = models.CharField(max_length=40)
    origin_location = models.ForeignKey(Location, blank=True, null=True)
    origin_year = models.IntegerField(blank=True, null=True)
    origin_exact = models.BooleanField(default=True)
    color_dominate_hex = RGBColorField(blank=True, null=True)
    color_secondary_hex = RGBColorField(blank=True, null=True)
    color_tertiary_hex = RGBColorField(blank=True, null=True)
    featured_image = ImageField(upload_to='featured-images', blank=True, null=True)
    generated_name = models.CharField(max_length=60, unique=True, blank=True, null=True)
    uses = models.ManyToManyField(FruitUsageType, blank=True, null=True)
    ripens_early_mod = models.CharField(max_length=1, default='m', choices=RIPENING_MODIFIER)
    ripens_early = models.IntegerField(blank=True, null=True, choices=RIPENING_MONTH_CHOICES, default=-1)
    ripens_late_mod = models.CharField(max_length=1, default='m', choices=RIPENING_MODIFIER)
    ripens_late = models.IntegerField(blank=True, null=True, choices=RIPENING_MONTH_CHOICES, default=-1)

    # Breeding Information
    chromosome_count = models.CharField(max_length=1, choices=CHROMOSOME_CHOICES, default='2', blank=True, null=True)
    parent_a = models.ForeignKey('Cultivar', blank=True, null=True, related_name='first_children')
    parent_b = models.ForeignKey('Cultivar', blank=True, null=True, related_name='second_children')

    # Descriptive Information
    brief_description = models.CharField(max_length=100, blank=True, null=True)
    history = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ('generated_name',)

    def save(self, *args, **kwargs):
        self.generated_name = self.__get_generated_name()
        return super(Cultivar, self).save(*args, **kwargs)

    def __str__(self):
        return self.generated_name or self.__get_generated_name()

    def __get_generated_name(self):
        return '{0} ({1})'.format(self.name, self.species.name)


class GenusImage(models.Model):
    genus_image_id = models.AutoField(primary_key=True)
    genus = models.ForeignKey(Genus)
    image = ImageField(upload_to='genus-images')
    name = models.CharField(max_length=20)
    description = models.CharField(max_length=300, blank=True, null=True)

    def __str__(self):
        return self.name


class SpeciesImage(models.Model):
    species_image_id = models.AutoField(primary_key=True)
    species = models.ForeignKey(Species)
    image = ImageField(upload_to='species-images')
    name = models.CharField(max_length=20)
    description = models.CharField(max_length=300, blank=True, null=True)

    def __str__(self):
        return self.name


class FruitingPlant(models.Model):
    """
    This is the main use model that is a specific plant in a specific location.
    Everything happens through this plant.
    """
    objects = FruitingPlantManager()
    fruiting_plant_id = models.AutoField(primary_key=True)
    created_by = models.ForeignKey(User)
    location = models.ForeignKey(Location)
    geocoordinate = models.ForeignKey(GeoCoordinate)
    species = models.ForeignKey(Species, null=True, blank=True)
    cultivar = models.ForeignKey(Cultivar, null=True, blank=True)
    date_planted = models.DateField(default=timezone.now)
    date_died = models.DateField(null=True, blank=True)

    def get_name(self):
        obj = self.species
        if self.cultivar:
            obj = self.cultivar
        return obj.generated_name

    def __str__(self):
        name = None
        if self.cultivar:
            name = str(self.cultivar)
        else:
            name = str(self.species)
        return '{0} - {1} @ {2}'.format(self.created_by, name, self.location)

    def save(self, *args, **kwargs):
        self.__clean_data()
        self.__validate()
        return super(FruitingPlant, self).save(*args, **kwargs)

    def __clean_data(self):
        if self.cultivar and not self.species:
            self.species = self.cultivar.species
        if self.cultivar and self.cultivar.species != self.species:
            self.species = self.cultivar.species

    def __validate(self):
        if not self.cultivar and not self.species:
            raise Exception('Must have a species or cultivar.')

openfruit/taxonomy/templates/taxonomy/add-cultivar.html
{% if popup %}<input type="hidden" name="_popup" value="1">{% endif %}

openfruit/taxonomy/templates/taxonomy/cultivar-detail.html
{% extends "base.html" %}
{% load openfruit_common_tags %}
{% load thumbnail %}
{% load staticfiles %}

{% block title %}OpenFruit - {{ cultivar.latin_name }}{% endblock %}

{% block breadcrumb %}
    <li><a href="{% url 'browse' %}">Browse</a></li>
    <li><a href="{% url 'genus-list' kingdom=kingdom.latin_name %}">{{ kingdom.latin_name }}</a></li>
    <li><a href="{% url 'genus-detail' kingdom=kingdom.latin_name genus=genus.latin_name %}">{{ genus.latin_name }}</a></li>
    <li><a href="{% url 'species-detail' kingdom=kingdom.latin_name genus=genus.latin_name species=species.latin_name %}">{{ species.latin_name }}</a></li>
    <li class="active">{{ cultivar.name }}</li>
{% endblock %}
{% block body %}
    <h1>{{ cultivar.generated_name }}</h1>
    {% if request.user.is_staff %}
        <div>
            <br>
        </div>
        <hr>
    {% endif %}
{% endblock %}

openfruit/taxonomy/templates/taxonomy/fruiting_plant_details.html
{% extends "base.html" %}
{% load taxonomy_tags %}

{% block body %}
    <div id="data">
    <h1>{% get_name_of_species_or_cultivar model.species model.cultivar %}</h1>
    <div class="row">
        <div class="col-sm-6">
            <strong>Created By:</strong> {{ model.created_by }}
        </div>
        <div class="col-sm-6">
            <strong>Date Planted:</strong> <span>{{ model.date_planted }}</span>
        </div>
        <div class="col-sm-6">
            <strong>Species: </strong> {{ model.species }}
        </div>
        <div class="col-sm-6">
            <strong>Cultivar: </strong> <span>{{ model.cultivar }}</span>
        </div>
        {% if model.date_died %}
            <div>
                <strong>Date Died:</strong> <span>{{ model.date_died }}</span>
            </div>
        {% endif %}
    </div>
    <div id="aggregate-reports">
        <h3>Aggregated Events</h3>
        <table class="table table-striped equal-table">
            <thead>
                <tr>
                    <td>J</td>
                    <td>F</td>
                    <td>M</td>
                    <td>A</td>
                    <td>M</td>
                    <td>J</td>
                    <td>J</td>
                    <td>A</td>
                    <td>S</td>
                    <td>O</td>
                    <td>N</td>
                    <td>D</td>
                </tr>
            </thead>
            <tbody>
            <tr>
                {% for leaf in leafs %}
                    <td>
                    {% if leaf %}
                        <i class="fa fa-leaf" aria-hidden="true"></i>
                    {% endif %}
                    </td>
                {% endfor %}
            </tr>
            <tr>
                {% for bloom in blooms %}
                    <td>
                        {% if bloom %}
                            <span>✿</span>
                        {% endif %}
                    </td>
                {% endfor %}
            </tr>
            <tr>
                {% for ripening in ripenings %}
                    <td>
                        {% if ripening %}
                            <i class="fa fa-apple" aria-hidden="true"></i>
                        {% endif %}
                    </td>
                {% endfor %}
            </tr>

            </tbody>
        </table>
    </div>
    {% if model.location %}
    <div>
        <h3>
            Located At: {{ model.location.name }}
        </h3>
    </div>
    {% endif %}
    <div id="map" class="small-google-map"></div>
    </div>
    {% if all_events %}
    <div id="events">}
       <h2>Logged Events</h2>
        {% for event in all_events %}
            <ul>
                <li>
                {{ event }}
                </li>
            </ul>
        {% endfor %}
    </div>
    {% else %}
    <div>
    <h2>No Events Logged</h2>
    </div>
    {% endif %}

{% endblock %}
{% block scripts %}
    <script>
        $(document).ready(function(){
            var map = null;
            var initMap = function() {
                var imageUrl = '{{ model.species.google_maps_image_url }}';
                var zoom = 19;
                var mapCenter = {lat: {{ model.geocoordinate.lat }}, lng: {{ model.geocoordinate.lon }}};
                map = new google.maps.Map(document.getElementById('map'), {
                    zoom: 19,
                    mapTypeId: 'hybrid',
                    center: mapCenter,
                    styles: [
                        {
                            featureType: 'poi.business',
                            stylers: [{visibility: 'off'}]
                        },
                        {
                            featureType: 'transit',
                            elementType: 'labels.icon',
                            stylers: [{visibility: 'off'}]
                        }
                    ]
                });
                var marker = new google.maps.Marker({
                    position: mapCenter,
                    map: map,
                    //title: "Select Location",
                    icon: imageUrl
                });
                console.log(map);
            };
            initMap();
            setTimeout(function(){
                google.maps.event.trigger(map, 'resize');
            }, 1000);
        });
    </script>
{% endblock %}

openfruit/taxonomy/templates/taxonomy/fruiting_plant_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head %}
    <script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
    {{ form.media }}
    <script type="text/javascript" src="{% url 'admin:jsi18n' %}"></script>
{% endblock %}
{% block body %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.fruiting_plant_id }}
        {{ form.species|as_crispy_field }}
        {{ form.cultivar|as_crispy_field }}
        {{ form.location|as_crispy_field }}
        {{ form.date_planted|as_crispy_field }}
        <label>Geocoordinate</label>
        <input id="id_lat" type="text" name="lat" hidden value="{{ center_lat }}">
        <input id="id_lon" type="text" name="lon" hidden value="{{ center_lon }}">
        {% include 'django_geo_db/geocoordinate.html' %}
        {% if popup %}<input type="hidden" name="_popup" value="1">{% endif %}
        <input class="btn btn-primary btn-lg pull-right" type="submit" value="Save">
    </form>
{% endblock %}
{% block scripts %}
{% endblock %}

openfruit/taxonomy/templates/taxonomy/genus.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}OpenFruit - {% if is_add %}Add{% else%}Edit{% endif %} Genus{% endblock %}

{% block breadcrumb %}
    <li><a href="{% url 'genus-list' kingdom='plantae' %}">Plantae</a></li>
    <li class="active">{% if is_add %}Add{% else %}Edit{% endif %} Genus</li>
{% endblock %}
{% block body %}
    <h1>{% if is_add %}Add{% else %}Edit{% endif %} Genus </h1>
    <div>
        <form action="" method="post" enctype='multipart/form-data'>
            {% csrf_token %}
            {{ form|crispy }}
            <input class="btn btn-default btn-lg" type="submit" value="Submit" />
            <input class="btn btn-primary btn-lg pull-right" name="add-new" type="submit" value="Submit Add Next" />
        </form>
    </div>
{% endblock %}
{% block scripts %}
    {{ form.media }}
{% endblock %}

openfruit/taxonomy/templates/taxonomy/species-detail.html
{% extends "base.html" %}
{% load openfruit_common_tags %}
{% load thumbnail %}
{% load staticfiles %}

{% block title %}OpenFruit - Genus {{ genus.latin_name }}{% endblock %}

{% block breadcrumb %}
    <li><a href="{% url 'browse' %}">Browse</a></li>
    <li><a href="{% url 'genus-list' kingdom=kingdom.latin_name %}">{{ kingdom.latin_name }}</a></li>
    <li><a href="{% url 'genus-detail' kingdom=kingdom.latin_name genus=genus.latin_name %}">{{ genus.latin_name }}</a></li>
    <li class="active">{{ species.latin_name }}</li>
{% endblock %}
{% block body %}
    {% if user.is_authenticated %}
        <h1>{{ species.name }} ({{ species.latin_name }}) <a href="{% url 'species' genus.genus_id species.species_id %}" class="btn btn-default">Edit</a></h1>
    {% else %}
        <h1>{{ species.name }} ({{ species.latin_name }})</h1>
    {% endif %}
    <div class="plant-metadata">
        {% if species.featured_image %}
            {% thumbnail species.featured_image "300x300" crop="center" as im %}
                <img class="pull-right plant-featured-image" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
            {% endthumbnail %}
        {% else %}
            <img src="{% static "img/not_available.jpg" %}" class="pull-right plant-featured-image" width="300" height="300">
        {% endif %}
    <span>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin dapibus facilisis dolor, id ornare tortor aliquam at. Nam sit amet hendrerit elit. Sed dapibus arcu non orci dignissim, at gravida lacus efficitur. Ut iaculis ut nisl in congue. Cras lacinia luctus ex id accumsan. Nunc porttitor tincidunt semper. Maecenas vulputate finibus commodo. Phasellus pellentesque leo in ex porta egestas. Vivamus at urna non tellus vulputate consectetur. Praesent pharetra est nec facilisis varius.

Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Pellentesque purus enim, interdum semper auctor vel, ullamcorper ut nibh. Cras mollis nisi id condimentum ultricies. Sed quis enim feugiat, commodo magna ac, tincidunt odio. Suspendisse semper, lorem dignissim accumsan placerat, arcu neque vestibulum risus, nec posuere nibh felis et elit. Aenean ac velit at ipsum ornare placerat at ut massa. Aenean elementum velit vel nulla elementum egestas.
    </span>
    </div>

    <h2>Cultivar List</h2>
    <h3>
    Birth Places
    </h3>
    <div class="google-map" id="map"></div>
    <hr>

    <div>
        {% if request.user.is_staff %}
            <div>
                <a class="btn btn-default btn-lg" href="#">Add Cultivar</a>
                <br>
            </div>
        {% endif %}
        {% for cultivar in cultivar_list %}
            <p class="group-item" >
                <a class="btn btn-default btn-lg btn-block list-group-item" href="{% url 'cultivar-detail' kingdom=kingdom.latin_name genus=genus.latin_name species=species.latin_name cultivar=cultivar.name %}">
                {% if species.featured_image %}
                    {% thumbnail cultivar.featured_image "50x50" crop="center" as im %}
                        <img class="list-thumbnail" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                    {% endthumbnail %}
                {% else %}
                    <img class="list-thumbnail" src="{% static 'img/not_available.jpg' %}" height="50" width="50"/>
                {% endif %}
                    {{ cultivar.name }}
                </a>
            </p>
        {% endfor %}
    </div>
{% endblock %}
{% block scripts %}
    <script src="{% static 'js/markerclusterer.js' %}"></script>
    <script src="https://cdn.rawgit.com/googlemaps/v3-utility-library/master/markerwithlabel/src/markerwithlabel.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sprintf/1.0.3/sprintf.js"></script>

    <script>
        function initMap() {
            var markers = [];
            var mapCenter = { lat: {{ GM_SETTINGS.lat }}, lng: {{ GM_SETTINGS.lon }}};
            var map = new google.maps.Map(document.getElementById('map'), {
                zoom: {{ GM_SETTINGS.zoom }},
                center: mapCenter
            });

            var setupCultivar = function(lat, lon, cultivarName, detailsUrl){
                var cultivarCenter = { lat: lat, lng: lon};
                var contentString = sprintf(`
                <div>
                    <h3>%s</h3>
                    <p>
                    </p>
                    <a class="btn btn-default btn-sm" href="%s">Details</a>
                </div>`, cultivarName, detailsUrl);
                var infowindow = new google.maps.InfoWindow({
                    content: contentString
                });
                var marker = new MarkerWithLabel({
                    position: cultivarCenter,
                    draggable: true,
                    map: map,
                    labelContent: sprintf('<div class="gmaps-label">%s</div>',cultivarName)
                });
                markers.push(marker);
                marker.addListener('click', function() {
                    infowindow.open(map, marker);
                });
                google.maps.event.addListener(marker, 'dragend', function(){
                    var position = marker.getPosition();
                    console.log(position);
                    console.log('lat:' + position.lat());
                    console.log('lng:' + position.lng());
                });
            };

            data = {};
            {% for cultivar in cultivar_list %}
                {% if cultivar.origin_location %}
                    var url = '{% url 'cultivar-detail' kingdom=cultivar.species.genus.kingdom.latin_name genus=cultivar.species.genus.latin_name species=cultivar.species.latin_name cultivar=cultivar.name %}';
                    setupCultivar({{ cultivar.origin_location.lat}}, {{ cultivar.origin_location.lon }}, '{{ cultivar.name }}', url);
                {% endif %}
            {% endfor %}
            var markerCluster = new MarkerClusterer(map, markers, {
                    imagePath: 'https://cdn.rawgit.com/googlemaps/js-marker-clusterer/gh-pages/images/m',
                    maxZoom: 18
            });
        }
        initMap();
    </script>
{% endblock %}