openfruit/urls.py
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.views.generic import TemplateView
from django.contrib import admin
from rest_framework import routers
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token, verify_jwt_token

from openfruit import settings
from openfruit.views import home, about, site_change, testing

router = routers.DefaultRouter()

urlpatterns = [

    url(r'^$', home, name='home'),
    url(r'^about/$', about, name='about'),
    url(r'^terms-of-service/$', TemplateView.as_view(template_name='terms-of-service.html'), name='terms-of-service'),
    url(r'^privacy/$', TemplateView.as_view(template_name='privacy-policy.html'), name='privacy-policy'),
    url(r'^request/site-change/$', site_change, name='site_change'),
    url(r'^admin/', include(admin.site.urls), name='admin'),

    # Authorization
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/v1/auth/token/$', obtain_jwt_token),
    url(r'^api/v1/auth/token/verify/$', verify_jwt_token),
    url(r'^api/v1/auth/token/refresh/$', refresh_jwt_token),
    url(r'^api/v1/auth/rest/', include('rest_auth.urls')),
    url(r'^api/v1/auth/allauth/', include('allauth.urls')),
    url(r'^', include('openfruit.ofauth.urls')),

    # Geo
    url(r'^api/v1/', include('django_geo_db.urls')),
    url(r'^api/v1/', include('django_geo_db.autocomplete_urls')),

    url(r'^', include('openfruit.common.urls')),
    url(r'^', include('openfruit.taxonomy.urls')),
    url(r'^', include('openfruit.reports.event.urls')),
    url(r'^', include('openfruit.reports.review.urls')),
    url(r'^', include('openfruit.userdata.urls')),
    url(r'^', include('openfruit.fruit_search.urls')),
    url(r'^', include('openfruit.geography.urls')),
    url(r'^', include('openfruit.fruit_reference.urls')),
    url(r'^', include('openfruit.reports.disease.urls')),
    url(r'^', include('openfruit.fruit_api.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += router.urls

if settings.DEBUG:
    urlpatterns += [url(r'^testing/$', testing, name='testing'),]

openfruit/userdata/urls.py
from django.conf.urls import url
from rest_framework import routers
from openfruit.userdata.views import SignupFormView

router = routers.DefaultRouter()

urlpatterns = [
    url(r'^signup/$', SignupFormView.as_view(), name='signup'),
]

openfruit/userdata/models.py
from django.db import models
from django.forms import ValidationError
from django.contrib.auth.models import User
from django_geo_db.models import Zipcode, Location


class Signup(models.Model):
    signup_id = models.AutoField(primary_key=True)
    user = models.OneToOneField(User, blank=True, null=True)
    username = models.CharField(max_length=20, unique=True)
    password = models.CharField(max_length=128)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    email = models.EmailField()
    zipcode = models.ForeignKey(Zipcode)
    new_location_lat_lon = models.CharField(max_length=20, blank=True, null=True)
    new_location_name = models.CharField(max_length=20, blank=True, null=True)
    existing_location = models.ForeignKey(Location, blank=True, null=True)
    organization = models.CharField(max_length=50, blank=True, null=True, help_text="If you belong to an organization such as a University, Business or Non-Profit, place it here.")
    request_to_be_a_curator = models.BooleanField(help_text="If you would like to become a curator.", default=False)
    reason_to_be_curator = models.TextField(help_text="A brief explination of why you should be considered for becoming a curator.", blank=True, null=True)


class UserProfile(models.Model):
    user_profile_id = models.AutoField(primary_key=True)
    user = models.OneToOneField(User)
    location = models.ForeignKey(Location)
    organization = models.CharField(max_length=50, blank=True, null=True, help_text="If you belong to an organization such as a University, Business or Non-Profit, place it here.")

    def __str__(self):
        return "{0}'s Profile".format(self.user.username)

openfruit/userdata/forms.py
from django.forms.models import ModelForm
from django.contrib.auth.models import User
from django import forms
from dal.autocomplete import ModelSelect2
from openfruit.userdata.models import Signup, UserProfile

class SignupForm(ModelForm):
    class Meta:
        model = Signup
        fields = ['username',
                  'password',
                  'first_name',
                  'last_name',
                  'email',
                  'zipcode',
                  'new_location_lat_lon',
                  'new_location_name',
                  'existing_location',
                  'organization',
                  'request_to_be_a_curator',
                  'reason_to_be_curator',
                  ]
        widgets = {
            'password': forms.PasswordInput(),
            'zipcode': ModelSelect2(url='zipcode-autocomplete'),
        }

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("Username already exists.")
        return username

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Email already exists.")
        return email


class UserProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = [
            'user',
            'location',
            'organization',
        ]
        widgets = {
            'location': ModelSelect2(url='named-location-autocomplete'),
        }

openfruit/userdata/views.py
import requests
from django.conf import settings
from django.http import HttpResponseRedirect
from django.views.generic import View
from django.contrib.auth.models import User
from django.shortcuts import render, reverse
from django.utils import timezone

from openfruit.common.services import setup_user_permissions_and_groups
from django_geo_db.models import GeoCoordinate, UserLocation
from django_geo_db.services import GEO_DAL
from django_geo_db.utilities import get_standardized_coordinate
from openfruit.userdata.models import UserProfile
from openfruit.userdata.forms import SignupForm


class SignupFormView(View):
    form_class = SignupForm
    initial = {'key': 'value'}
    template_name = 'userdata/signup.html'

    def __does_captcha_validate(self, captcha):
        secret = '6LdkER8UAAAAAIsCOzmyIhbEYDi0rngvu8y9pjcM',
        googleUrl = 'https://www.google.com/recaptcha/api/siteverify?secret={0}&response={1}'.format(secret, captcha)
        headers = {'content-type': 'application/json'}
        response = requests.post(googleUrl, headers=headers)
        responseData = response.json()
        return responseData['success']

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return HttpResponseRedirect('/')
        form = self.form_class(initial=self.initial)
        data = {
            'form': form,
            'map_center': settings.DEFAULT_MAP_CENTER,
            'zipcode': '',
        }
        return render(request, self.template_name, data)

    def post(self, request, *args, **kwargs):
        data = request.POST.copy()
        center = settings.DEFAULT_MAP_CENTER
        if 'new_location_lat_lon' in request.POST and request.POST['new_location_lat_lon']:
            center = request.POST['new_location_lat_lon'].split(' ', 2)
            lat = get_standardized_coordinate(center[0])
            lon = get_standardized_coordinate(center[1])
            data['new_location_lat_lon'] = '{0} {1}'.format(lat, lon)

        zipcode = data['zipcode']
        zipcodeFailed = False
        hasMoved = 'location-moved' in data and data['location-moved'] == 'moved'
        isNewLocation = data['location'] == 'new-location'

        if hasMoved:
            if zipcode:
                try:
                    data['zipcode'] = GEO_DAL.get_zipcode_by_zip(zipcode).zipcode_id
                except:
                    zipcodeFailed = True
        if not isNewLocation:
            locationID = data['existing_location']
            location = GEO_DAL.get_location_by_id(locationID)
            zipcode = location.zipcode
            if not zipcode:
                zipcode = GEO_DAL.geocode_zipcode_from_lat_lon(location.lat(), location.lon())
            data['zipcode'] = zipcode.zipcode_id

        form = self.form_class(data)
        isValid = True
        if not hasMoved and isNewLocation:
            form.add_error('__all__', 'Select a New Location.')
            isValid = False
        if zipcodeFailed:
            form.add_error('__all__', 'Zipcode could not be found.')
            isValid = False
        if form.is_valid() and isValid:
            """ TODO: REMOVE THE COMMENTS
            captcha = request.POST['g-recaptcha-response']
            captchaValidates = self.__does_captcha_validate(captcha)
            """
            captchaValidates = True
            if captchaValidates:
                signupModel = form.save(commit=False)
                valid = True
                locationError = self.__validate_location_return_error_or_location(isNewLocation, signupModel)
                if locationError:
                    form.add_error('__all__', locationError)
                    valid = False
                if valid:
                    location = None
                    if isNewLocation:
                        zipcode = signupModel.zipcode
                        latLon = signupModel.new_location_lat_lon
                        locationName = signupModel.new_location_name
                        lat, lon = latLon.split(' ')
                        coord, created = GeoCoordinate.objects.get_or_create(lat=lat, lon=lon)
                        location = GEO_DAL.create_location(zipcode, coord, locationName)
                    else:
                        location = signupModel.existing_location

                    try:
                        user = User(username=signupModel.username,
                                    first_name=signupModel.first_name,
                                    last_name=signupModel.last_name,
                                    email=signupModel.email,
                                    )
                        user.set_password(signupModel.password)
                        user.save()
                        setup_user_permissions_and_groups(user)
                        user.save()
                    except Exception as e:
                        form.add_error('__all__', e)
                        valid = False
                        try:
                            user.delete()
                        except:
                            pass

                    if valid:

                        userProfile = UserProfile(
                            organization=signupModel.organization,
                            location=location,
                            user=user
                        )
                        userProfile.save()

                        if isNewLocation:
                            userLocation = UserLocation(user=user, location=location, last_used=timezone.now(), user_created=True)
                        else:
                            userLocation = UserLocation(user=user, location=location, last_used=timezone.now(), user_created=False)
                        userLocation.save()

                        loginUrl = reverse('admin:login')
                        return HttpResponseRedirect(loginUrl)
            else:
                form.add_error('__all__', 'Captcha did not validate.')
        data = {
            'form': form,
            'map_center': center,
            'has_moved': hasMoved,
            'zipcode': zipcode,
        }
        return render(request, self.template_name, data)

    def __validate_location_return_error_or_location(self, isNewLocation, model):
        if isNewLocation:
            zipcode = model.zipcode
            latLon = model.new_location_lat_lon
            locationName = model.new_location_name
            if not zipcode:
                return 'Zipcode needed.'
            if not latLon:
                return 'Latitude and Longitude needed.'
            if not locationName:
                return 'Need name of the new location.'
        else:
            if not model.existing_location:
                return 'Need a value for an existing location.'



def signup(request):
    form = SignupForm()
    data = {
        'form': form,
        'DEFAULT_MAP_CENTER': settings.DEFAULT_MAP_CENTER,
    }
    return render(template_name='signup.html', context=data, request=request)

openfruit/userdata/templates/userdata/signup.html
{% extends "base.html" %}
{% load rest_framework %}
{% load staticfiles %}
{% load openfruit_common_tags %}
{% load crispy_forms_tags %}

{% block title %}OpenFruit - Signup{% endblock %}
{% block  body %}

    <h1>Signup for OpenFruit</h1>
    <div class="container">
    {% if form.errors %}
        <h3>Errors</h3>
        <div id="errors">
            <ul>
                {% for field, errors in form.errors.items %}
                    {% if field == '__all__' %}
                        {% for error in errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
    {% endif %}
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.username|as_crispy_field }}
            {{ form.password|as_crispy_field }}
            {{ form.first_name|as_crispy_field }}
            {{ form.last_name|as_crispy_field }}
            {{ form.email|as_crispy_field }}
            {{ form.organization|as_crispy_field }}
            {{ form.request_to_be_a_curator|as_crispy_field }}
            {{ form.reason_to_be_curator|as_crispy_field }}
            <div id="signup-location">
                <h3>Where will you be posting from mostly?</h3>
                <p>This should be your home, your business, a farm, etc.</p>
                <div class="contrast-banner text-center">
                    <label class="radio-inline">
                        <input id="new-location" class="radio-show large-radio" checked="checked" type="radio" name="location" value="new-location" data-target="#new-location-select">New Location <span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>
                    </label>
                    <label class="radio-inline">
                        <input class="radio-show large-radio" type="radio" name="location" value="existing-location" data-target="#existing-location-select">Existing Location
                    </label>
                </div>

                <div id="new-location-select">
                    {{ form.new_location_lat_lon.as_hidden }}
                    {{ form.new_location_name|as_crispy_field }}
                    <div>
                        <p>Your Lat Lon: <span id="new-lat-lon"></span></p>
                    </div>
                    <div>
                        <p>Your Zipcode:<span id="zipcode-display"></span></p>
                        <input hidden id="zipcode" name="zipcode" type="text"
                               {% if zipcode %}
                                   value="{{ zipcode }}"
                               {% endif %}
                               >
                    </div>
                    <div id="map" class="google-map"></div>
                    <input id="location-moved" name="location-moved" type="text"
                           {% if has_moved %}
                               value="moved"
                           {% endif %}
                           hidden>
                </div>
                <div id="existing-location-select" >
                    <div id="existing-location-text">Location:</div>
                    <div id="existing-location-map" class="google-map"></div>
                    <input id="existing_location" name="existing_location" type="text" hidden>
                </div>
            </div>

            <!--<div class="g-recaptcha" data-sitekey="6LdkER8UAAAAAE7YK0SkbBxWJ23zX5tpGQ_cpRs1"></div>-->
            <br>
            <input id="submit" type="submit" class="btn btn-primary btn-lg pull-right" value="Submit" disabled>
        </form>
    </div>
{% endblock %}
{% block scripts %}
    <script src="https://cdn.rawgit.com/googlemaps/v3-utility-library/master/markerwithlabel/src/markerwithlabel.js"></script>
    <script src="{% static 'js/markerclusterer.js' %}"></script>
    <script src="{% static 'js/common/radio-show.js' %}"></script>
    <script src="{% static 'js/easy_rest_data.js' %}"></script>
    <script src="{% static 'js/geography/geography-service.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sprintf/1.0.3/sprintf.js"></script>
    <script>
    /*
    Validation logic for btn
    If New Location
    - Name must be typed.
    - Zipcode and Latlon must exist.

    if existing location is selected
    - input cannot be empty
     */
        var radioShow = new openfruit.common.RadioShow();
        var newLatLon = $('#new-lat-lon');
        var locationLatLon = $('#id_new_location_lat_lon');
        var existingLocationLatLon = $('#id_existing_location');
        var locationMovedInput = $('#location-moved');
        var zipcode = $('#zipcode');
        var zipcodeDisplay = $('#zipcode-display');
        var radioButtons = $('input[name=location]');
        var submitButton = $('#submit');
        var locations = null;
        var easyData = new openfruit.EasyRestData();
        var geographyService = new django_geo_db.GeographyService(easyData);

        var isNewLocationChecked = function() {
            var checked = $('input[name=location]:checked').val();
            if (checked == 'new-location'){
                return true;
            }
            else{
                return false;
            }
        };


        var validateLocation = function(){
            if (isNewLocationChecked()){
                var moved = locationMovedInput.val();
                if (moved == 'moved'){
                    var locationNameObj = $('#id_new_location_name');
                    var locationName = locationNameObj.val();
                    if (locationName !== '' && locationName !== undefined){
                        submitButton.prop('disabled', false);
                        return;
                    }
                    else{
                        submitButton.prop('disabled', true);
                        return;
                    }
                }
                else{
                    submitButton.prop('disabled', true);
                    return;
                }
            }
            else{
                /*
                var existingLocationValue = $( "#id_existing_location option:selected" ).text();
                if (existingLocationValue !== '---------'){
                    submitButton.prop('disabled', false);
                }
                else{
                    submitButton.prop('disabled', true);
                }
                */
                var text = $('#existing-location-text').text();
                if (text !== 'Location:'){
                    submitButton.prop('disabled', false);
                }
                else{
                    submitButton.prop('disabled', true);
                }
            }
        };
        radioButtons.click(function(){
            validateLocation();
            if (!isNewLocationChecked() && locations === null){
                setupExistingMap();
            }
        });
        $('#id_new_location_name').on('input propertychange paste', function() {
            validateLocation();
        });

        var geoCodeLocation = function (marker){
            var position = marker.getPosition();
            var latlng = new google.maps.LatLng(position.lat(), position.lng());
            geocoder = new google.maps.Geocoder();

            geocoder.geocode({'latLng': latlng}, function(results, status) {
                if (status == google.maps.GeocoderStatus.OK) {
                    if (results[0]) {
                        for (j = 0; j < results[0].address_components.length; j++) {
                            if (results[0].address_components[j].types[0] == 'postal_code') {
                                var value  = results[0].address_components[j].short_name;
                                zipcodeDisplay.text(value);
                                zipcode.val(value);
                            }
                        }
                    }
                } else {
                    alert('Zipcode look up failed. Make sure the arrow is over the US.');
                    console.log("Failed to find zipcode: " + status);
                }
            });
        };

        var setupExistingMap = function(){
            var mapCenter = { lat: {{ map_center.0 }}, lng: {{ map_center.1 }}};
            var map = new google.maps.Map(document.getElementById('existing-location-map'), {
                zoom: 4,
                center: mapCenter
            });
            var homeIcon = 'http://maps.google.com/mapfiles/kml/pal3/icon23.png';
            locations = {};
            geographyService.get_public_locations(function(locations){
                var markers = [];
                var markerCluster = new MarkerClusterer(map, [], {
                    imagePath: 'https://cdn.rawgit.com/googlemaps/js-marker-clusterer/gh-pages/images/m',
                    maxZoom: 18
                });
                for (var index in locations) {
                    var obj = locations[index];
                    locations.push(obj);
                    data = {
                        position: {lat:parseFloat(obj.lat), lng:parseFloat(obj.lon)},
                        map: map,
                        title: obj.name,
                        icon: homeIcon,
                        labelContent: sprintf('<div class="gmaps-label">%s</div>', obj.name)
                    };
                    marker = new MarkerWithLabel(data);
                    markerCluster.addMarker(marker, true);
                    new function(theObj){
                        marker.addListener('click', function () {
                            var div = $('#existing-location-text');
                            div.text('Location:' + theObj.name);
                            div.addClass('alert alert-success');
                            $('#existing_location').val(theObj.location_id);
                            validateLocation();
                        });
                    }(obj);
                }
            });
            setTimeout(function(){
                google.maps.event.trigger(map, 'resize');
            }, 1000);
        };

        var initMap = function() {
            var mapCenter = { lat: {{ map_center.0 }}, lng: {{ map_center.1 }}};
            var map = new google.maps.Map(document.getElementById('map'), {
                zoom: 4,
                center: mapCenter
            });
            var marker = new google.maps.Marker({
                position: mapCenter,
                draggable: true,
                title: "Select Location",
                map: map
            });
            google.maps.event.addListener(marker, 'dragend', function () {
                var position = marker.getPosition();
                var value = '' + parseFloat(position.lat()).toFixed(5) + ' ' + parseFloat(position.lng()).toFixed(5);
                locationLatLon.val(value);
                newLatLon.html(value);
                locationMovedInput.val('moved');
                geoCodeLocation(marker);
                validateLocation();
            });
        };
        initMap();
        setTimeout(function(){
            google.maps.event.trigger(map, 'resize');
        }, 1000);
        validateLocation();


        var curatorCheckbox = $('#id_request_to_be_a_curator');
        var curatorSection = $('#div_id_reason_to_be_curator');
        curatorSection.hide();
        curatorCheckbox.click(function() {
            $('#div_id_reason_to_be_curator')[this.checked ? "show" : "hide"]();
        });
    </script>
{{ form.media }}
{% endblock %}